# Generated by Django 5.2.1 on 2025-08-28 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_user_employee_created_by_and_more'),
        ('performance', '0002_remove_performance_employee_performance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='user',
        ),
        migrations.AddField(
            model_name='performance',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='employees.employee'),
            preserve_default=False,
        ),
    ]
